eureka:
  client:
    serviceUrl:
      defaultZone: http://118.25.54.197:8761/eureka/
  instance:
    prefer-ip-address: false
    lease-expiration-duration-in-seconds: 90    # 过期时间
    lease-renewal-interval-in-seconds: 28    # 续约间隔


spring:
  output:
    ansi:
      enabled: ALWAYS