test:
  prop: test-prop-2

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    maxActive: 20
    maxWait: 60000
    initialSize: 1
    validationQuery: 'select "x"'
    dbType: mysql
    url: jdbc:mysql://118.25.54.197/aiclub?useSSL=false&serverTimezone=UTC
    username: uetty
    password: '{cipher}AQAQA9PslvAtvJSwg/bjzgnYYZDX65TLOkqGd9iLC4Y9gy8PE4uZjsSZGRfS6y+yGCmri/ypiq+5MvldLl8RXeV1847LHBQKc0cl1Hg/z4pVp9MN2q80MXFUmfwXLJPlrFwlgupmTqkHu18L4ZGd3disN6sy+GxCQB8TguRxXZpIdqIOg2ty999Jd4qY+DFU7L8sP4z7zn4dbCwUuQaj6TuhixA1U+cS1P+OCOFLLk6vYn7aiOwgJI/dnZM4OBqblGle3QIybsF4VfxyqOlSCqz4LesdTYnNlVTJnrgkUzDZ0B+eAaEgiNbaY5V7gTOmSGbAxk/s3qMfSgunxpCO4GKD8D5+jOd9fdCGHUd+60SdDHUtvrkQ2F6PkcZFi4Yy7JA='
